Promise.all([
  ["@color.Background.Brand.Default", "var(--mon-color-background-brand-default)", "Bg/Brand/Default"],
  ["@color.Background.Brand.Hover", "var(--mon-color-background-brand-hover)", "Bg/Brand/Hover"],
  ["@color.Background.Brand.Secondary Hover", "var(--mon-color-background-brand-secondary-hover)", "Bg/Brand/Secondary Hover"],
  ["@color.Background.Brand.Secondary", "var(--mon-color-background-brand-secondary)", "Bg/Brand/Secondary"],
  ["@color.Background.Brand.Tertiary Hover", "var(--mon-color-background-brand-tertiary-hover)", "Bg/Brand/Tertiary Hover"],
  ["@color.Background.Brand.Tertiary", "var(--mon-color-background-brand-tertiary)", "Bg/Brand/Tertiary"],
  ["@color.Background.Danger.Default", "var(--mon-color-background-danger-default)", "Bg/Danger/Default"],
  ["@color.Background.Danger.Hover", "var(--mon-color-background-danger-hover)", "Bg/Danger/Hover"],
  ["@color.Background.Danger.Secondary Hover", "var(--mon-color-background-danger-secondary-hover)", "Bg/Danger/Secondary Hover"],
  ["@color.Background.Danger.Secondary", "var(--mon-color-background-danger-secondary)", "Bg/Danger/Secondary"],
  ["@color.Background.Danger.Tertiary Hover", "var(--mon-color-background-danger-tertiary-hover)", "Bg/Danger/Tertiary Hover"],
  ["@color.Background.Danger.Tertiary", "var(--mon-color-background-danger-tertiary)", "Bg/Danger/Tertiary"],
  ["@color.Background.Default.Default Hover", "var(--mon-color-background-default-default-hover)", "Bg/Default/Default Hover"],
  ["@color.Background.Default.Default", "var(--mon-color-background-default-default)", "Bg/Default/Default"],
  ["@color.Background.Default.Secondary Hover", "var(--mon-color-background-default-secondary-hover)", "Bg/Default/Secondary Hover"],
  ["@color.Background.Default.Secondary", "var(--mon-color-background-default-secondary)", "Bg/Default/Secondary"],
  ["@color.Background.Default.Tertiary Hover", "var(--mon-color-background-default-tertiary-hover)", "Bg/Default/Tertiary Hover"],
  ["@color.Background.Default.Tertiary", "var(--mon-color-background-default-tertiary)", "Bg/Default/Tertiary"],
  ["@color.Background.Disabled.Default", "var(--mon-color-background-disabled-default)", "Bg/Disabled/Default"],
  ["@color.Background.Neutral.Default", "var(--mon-color-background-neutral-default)", "Bg/Neutral/Default"],
  ["@color.Background.Neutral.Hover", "var(--mon-color-background-neutral-hover)", "Bg/Neutral/Hover"],
  ["@color.Background.Neutral.Secondary Hover", "var(--mon-color-background-neutral-secondary-hover)", "Bg/Neutral/Secondary Hover"],
  ["@color.Background.Neutral.Secondary", "var(--mon-color-background-neutral-secondary)", "Bg/Neutral/Secondary"],
  ["@color.Background.Neutral.Tertiary Hover", "var(--mon-color-background-neutral-tertiary-hover)", "Bg/Neutral/Tertiary Hover"],
  ["@color.Background.Neutral.Tertiary", "var(--mon-color-background-neutral-tertiary)", "Bg/Neutral/Tertiary"],
  ["@color.Background.Positive.Default", "var(--mon-color-background-positive-default)", "Bg/Positive/Default"],
  ["@color.Background.Positive.Hover", "var(--mon-color-background-positive-hover)", "Bg/Positive/Hover"],
  ["@color.Background.Positive.Secondary Hover", "var(--mon-color-background-positive-secondary-hover)", "Bg/Positive/Secondary Hover"],
  ["@color.Background.Positive.Secondary", "var(--mon-color-background-positive-secondary)", "Bg/Positive/Secondary"],
  ["@color.Background.Positive.Tertiary Hover", "var(--mon-color-background-positive-tertiary-hover)", "Bg/Positive/Tertiary Hover"],
  ["@color.Background.Positive.Tertiary", "var(--mon-color-background-positive-tertiary)", "Bg/Positive/Tertiary"],
  ["@color.Background.Utilities.Blanket", "var(--mon-color-background-utilities-blanket)", "Bg/Utilities/Blanket"],
  ["@color.Background.Utilities.Measurement", "var(--mon-color-background-utilities-measurement)", "Bg/Utilities/Measurement"],
  ["@color.Background.Utilities.Overlay", "var(--mon-color-background-utilities-overlay)", "Bg/Utilities/Overlay"],
  ["@color.Background.Utilities.Scrim", "var(--mon-color-background-utilities-scrim)", "Bg/Utilities/Scrim"],
  ["@color.Background.Warning.Default", "var(--mon-color-background-warning-default)", "Bg/Warning/Default"],
  ["@color.Background.Warning.Hover", "var(--mon-color-background-warning-hover)", "Bg/Warning/Hover"],
  ["@color.Background.Warning.Secondary Hover", "var(--mon-color-background-warning-secondary-hover)", "Bg/Warning/Secondary Hover"],
  ["@color.Background.Warning.Secondary", "var(--mon-color-background-warning-secondary)", "Bg/Warning/Secondary"],
  ["@color.Background.Warning.Tertiary Hover", "var(--mon-color-background-warning-tertiary-hover)", "Bg/Warning/Tertiary Hover"],
  ["@color.Background.Warning.Tertiary", "var(--mon-color-background-warning-tertiary)", "Bg/Warning/Tertiary"],
  ["@color.Border.Brand.Default", "var(--mon-color-border-brand-default)", ""],
  ["@color.Border.Brand.Secondary", "var(--mon-color-border-brand-secondary)", ""],
  ["@color.Border.Brand.Tertiary", "var(--mon-color-border-brand-tertiary)", ""],
  ["@color.Border.Danger.Default", "var(--mon-color-border-danger-default)", ""],
  ["@color.Border.Danger.Secondary", "var(--mon-color-border-danger-secondary)", ""],
  ["@color.Border.Danger.Tertiary", "var(--mon-color-border-danger-tertiary)", ""],
  ["@color.Border.Default.Default", "var(--mon-color-border-default-default)", ""],
  ["@color.Border.Default.Secondary", "var(--mon-color-border-default-secondary)", ""],
  ["@color.Border.Default.tertiary", "var(--mon-color-border-default-tertiary)", ""],
  ["@color.Border.Disabled.default", "var(--mon-color-border-disabled-default)", ""],
  ["@color.Border.Neutral.Default", "var(--mon-color-border-neutral-default)", ""],
  ["@color.Border.Neutral.Secondary", "var(--mon-color-border-neutral-secondary)", ""],
  ["@color.Border.Neutral.tertiary", "var(--mon-color-border-neutral-tertiary)", ""],
  ["@color.Border.Positive.Default", "var(--mon-color-border-positive-default)", ""],
  ["@color.Border.Positive.Secondary", "var(--mon-color-border-positive-secondary)", ""],
  ["@color.Border.Positive.tertiary", "var(--mon-color-border-positive-tertiary)", ""],
  ["@color.Border.Utilities.Measurement", "var(--mon-color-border-utilities-measurement)", ""],
  ["@color.Border.Utilities.Swatch", "var(--mon-color-border-utilities-swatch)", ""],
  ["@color.Border.Warning.Default", "var(--mon-color-border-warning-default)", ""],
  ["@color.Border.Warning.Secondary", "var(--mon-color-border-warning-secondary)", ""],
  ["@color.Border.Warning.tertiary", "var(--mon-color-border-warning-tertiary)", ""],
  ["@color.Icon.Brand.Default", "var(--mon-color-icon-brand-default)", ""],
  ["@color.Icon.Brand.On Brand Secondary", "var(--mon-color-icon-brand-on-brand-secondary)", ""],
  ["@color.Icon.Brand.On Brand Tertiary", "var(--mon-color-icon-brand-on-brand-tertiary)", ""],
  ["@color.Icon.Brand.On Brand", "var(--mon-color-icon-brand-on-brand)", ""],
  ["@color.Icon.Brand.Secondary", "var(--mon-color-icon-brand-secondary)", ""],
  ["@color.Icon.Brand.Tertiary", "var(--mon-color-icon-brand-tertiary)", ""],
  ["@color.Icon.Danger.Default", "var(--mon-color-icon-danger-default)", ""],
  ["@color.Icon.Danger.On Danger Secondary", "var(--mon-color-icon-danger-on-danger-secondary)", ""],
  ["@color.Icon.Danger.On Danger Tertiary", "var(--mon-color-icon-danger-on-danger-tertiary)", ""],
  ["@color.Icon.Danger.On Danger", "var(--mon-color-icon-danger-on-danger)", ""],
  ["@color.Icon.Danger.Secondary", "var(--mon-color-icon-danger-secondary)", ""],
  ["@color.Icon.Danger.Tertiary", "var(--mon-color-icon-danger-tertiary)", ""],
  ["@color.Icon.Default.Default", "var(--mon-color-icon-default-default)", ""],
  ["@color.Icon.Default.Secondary", "var(--mon-color-icon-default-secondary)", ""],
  ["@color.Icon.Default.Tertiary", "var(--mon-color-icon-default-tertiary)", ""],
  ["@color.Icon.Disabled.Default", "var(--mon-color-icon-disabled-default)", ""],
  ["@color.Icon.Disabled.On Disabled", "var(--mon-color-icon-disabled-on-disabled)", ""],
  ["@color.Icon.Neutral.Default", "var(--mon-color-icon-neutral-default)", ""],
  ["@color.Icon.Neutral.On Neutral Secondary", "var(--mon-color-icon-neutral-on-neutral-secondary)", ""],
  ["@color.Icon.Neutral.On Neutral Tertiary", "var(--mon-color-icon-neutral-on-neutral-tertiary)", ""],
  ["@color.Icon.Neutral.On Neutral", "var(--mon-color-icon-neutral-on-neutral)", ""],
  ["@color.Icon.Neutral.Secondary", "var(--mon-color-icon-neutral-secondary)", ""],
  ["@color.Icon.Neutral.Tertiary", "var(--mon-color-icon-neutral-tertiary)", ""],
  ["@color.Icon.Positive.Default", "var(--mon-color-icon-positive-default)", ""],
  ["@color.Icon.Positive.On Positive Secondary", "var(--mon-color-icon-positive-on-positive-secondary)", ""],
  ["@color.Icon.Positive.On Positive Tertiary", "var(--mon-color-icon-positive-on-positive-tertiary)", ""],
  ["@color.Icon.Positive.On Positive", "var(--mon-color-icon-positive-on-positive)", ""],
  ["@color.Icon.Positive.Secondary", "var(--mon-color-icon-positive-secondary)", ""],
  ["@color.Icon.Positive.Tertiary", "var(--mon-color-icon-positive-tertiary)", ""],
  ["@color.Icon.Utilities.Icon On Measurement", "var(--mon-color-icon-utilities-icon-on-measurement)", ""],
  ["@color.Icon.Utilities.Icon", "var(--mon-color-icon-utilities-icon)", ""],
  ["@color.Icon.Warning.Default", "var(--mon-color-icon-warning-default)", ""],
  ["@color.Icon.Warning.On Warning Secondary", "var(--mon-color-icon-warning-on-warning-secondary)", ""],
  ["@color.Icon.Warning.On Warning Tertiary", "var(--mon-color-icon-warning-on-warning-tertiary)", ""],
  ["@color.Icon.Warning.On Warning", "var(--mon-color-icon-warning-on-warning)", ""],
  ["@color.Icon.Warning.Secondary", "var(--mon-color-icon-warning-secondary)", ""],
  ["@color.Icon.Warning.Tertiary", "var(--mon-color-icon-warning-tertiary)", ""],
  ["@color.Text.Brand.Default", "var(--mon-color-text-brand-default)", ""],
  ["@color.Text.Brand.On Brand Secondary", "var(--mon-color-text-brand-on-brand-secondary)", ""],
  ["@color.Text.Brand.On Brand Tertiary", "var(--mon-color-text-brand-on-brand-tertiary)", ""],
  ["@color.Text.Brand.On Brand", "var(--mon-color-text-brand-on-brand)", ""],
  ["@color.Text.Brand.Secondary", "var(--mon-color-text-brand-secondary)", ""],
  ["@color.Text.Brand.Tertiary", "var(--mon-color-text-brand-tertiary)", ""],
  ["@color.Text.Danger.Default", "var(--mon-color-text-danger-default)", ""],
  ["@color.Text.Danger.On Danger Secondary", "var(--mon-color-text-danger-on-danger-secondary)", ""],
  ["@color.Text.Danger.On Danger Tertiary", "var(--mon-color-text-danger-on-danger-tertiary)", ""],
  ["@color.Text.Danger.On Danger", "var(--mon-color-text-danger-on-danger)", ""],
  ["@color.Text.Danger.Secondary", "var(--mon-color-text-danger-secondary)", ""],
  ["@color.Text.Danger.Tertiary", "var(--mon-color-text-danger-tertiary)", ""],
  ["@color.Text.Default.Default", "var(--mon-color-text-default-default)", ""],
  ["@color.Text.Default.Secondary", "var(--mon-color-text-default-secondary)", ""],
  ["@color.Text.Default.Tertiary", "var(--mon-color-text-default-tertiary)", ""],
  ["@color.Text.Disabled.Default", "var(--mon-color-text-disabled-default)", ""],
  ["@color.Text.Disabled.On Disabled", "var(--mon-color-text-disabled-on-disabled)", ""],
  ["@color.Text.Neutral.Default", "var(--mon-color-text-neutral-default)", ""],
  ["@color.Text.Neutral.On Neutral Secondary", "var(--mon-color-text-neutral-on-neutral-secondary)", ""],
  ["@color.Text.Neutral.On Neutral Tertiary", "var(--mon-color-text-neutral-on-neutral-tertiary)", ""],
  ["@color.Text.Neutral.On Neutral", "var(--mon-color-text-neutral-on-neutral)", ""],
  ["@color.Text.Neutral.Secondary", "var(--mon-color-text-neutral-secondary)", ""],
  ["@color.Text.Neutral.Tertiary", "var(--mon-color-text-neutral-tertiary)", ""],
  ["@color.Text.Positive.Default", "var(--mon-color-text-positive-default)", ""],
  ["@color.Text.Positive.On Positive Secondary", "var(--mon-color-text-positive-on-positive-secondary)", ""],
  ["@color.Text.Positive.On Positive Tertiary", "var(--mon-color-text-positive-on-positive-tertiary)", ""],
  ["@color.Text.Positive.On Positive", "var(--mon-color-text-positive-on-positive)", ""],
  ["@color.Text.Positive.Secondary", "var(--mon-color-text-positive-secondary)", ""],
  ["@color.Text.Positive.Tertiary", "var(--mon-color-text-positive-tertiary)", ""],
  ["@color.Text.Utilities.Text On Measurement", "var(--mon-color-text-utilities-text-on-measurement)", ""],
  ["@color.Text.Utilities.Text On Overlay", "var(--mon-color-text-utilities-text-on-overlay)", ""],
  ["@color.Text.Warning.Default", "var(--mon-color-text-warning-default)", ""],
  ["@color.Text.Warning.On Warning Secondary", "var(--mon-color-text-warning-on-warning-secondary)", ""],
  ["@color.Text.Warning.On Warning Tertiary", "var(--mon-color-text-warning-on-warning-tertiary)", ""],
  ["@color.Text.Warning.On Warning", "var(--mon-color-text-warning-on-warning)", ""],
  ["@color.Text.Warning.Secondary", "var(--mon-color-text-warning-secondary)", ""],
  ["@color.Text.Warning.Tertiary", "var(--mon-color-text-warning-tertiary)", ""],
  ["@color_primitives.Black.100", "var(--mon-color-black-100)", ""],
  ["@color_primitives.Black.1000", "var(--mon-color-black-1000)", ""],
  ["@color_primitives.Black.200", "var(--mon-color-black-200)", ""],
  ["@color_primitives.Black.300", "var(--mon-color-black-300)", ""],
  ["@color_primitives.Black.400", "var(--mon-color-black-400)", ""],
  ["@color_primitives.Black.500", "var(--mon-color-black-500)", ""],
  ["@color_primitives.Black.600", "var(--mon-color-black-600)", ""],
  ["@color_primitives.Black.700", "var(--mon-color-black-700)", ""],
  ["@color_primitives.Black.800", "var(--mon-color-black-800)", ""],
  ["@color_primitives.Black.900", "var(--mon-color-black-900)", ""],
  ["@color_primitives.Blue.100", "var(--mon-color-blue-100)", ""],
  ["@color_primitives.Blue.1000", "var(--mon-color-blue-1000)", ""],
  ["@color_primitives.Blue.200", "var(--mon-color-blue-200)", ""],
  ["@color_primitives.Blue.300", "var(--mon-color-blue-300)", ""],
  ["@color_primitives.Blue.400", "var(--mon-color-blue-400)", ""],
  ["@color_primitives.Blue.500", "var(--mon-color-blue-500)", ""],
  ["@color_primitives.Blue.600", "var(--mon-color-blue-600)", ""],
  ["@color_primitives.Blue.700", "var(--mon-color-blue-700)", ""],
  ["@color_primitives.Blue.800", "var(--mon-color-blue-800)", ""],
  ["@color_primitives.Blue.900", "var(--mon-color-blue-900)", ""],
  ["@color_primitives.Brand.100", "var(--mon-color-brand-100)", ""],
  ["@color_primitives.Brand.1000", "var(--mon-color-brand-1000)", ""],
  ["@color_primitives.Brand.200", "var(--mon-color-brand-200)", ""],
  ["@color_primitives.Brand.300", "var(--mon-color-brand-300)", ""],
  ["@color_primitives.Brand.400", "var(--mon-color-brand-400)", ""],
  ["@color_primitives.Brand.500", "var(--mon-color-brand-500)", ""],
  ["@color_primitives.Brand.600", "var(--mon-color-brand-600)", ""],
  ["@color_primitives.Brand.700", "var(--mon-color-brand-700)", ""],
  ["@color_primitives.Brand.800", "var(--mon-color-brand-800)", ""],
  ["@color_primitives.Brand.900", "var(--mon-color-brand-900)", ""],
  ["@color_primitives.Gray.100", "var(--mon-color-gray-100)", ""],
  ["@color_primitives.Gray.1000", "var(--mon-color-gray-1000)", ""],
  ["@color_primitives.Gray.200", "var(--mon-color-gray-200)", ""],
  ["@color_primitives.Gray.300", "var(--mon-color-gray-300)", ""],
  ["@color_primitives.Gray.400", "var(--mon-color-gray-400)", ""],
  ["@color_primitives.Gray.500", "var(--mon-color-gray-500)", ""],
  ["@color_primitives.Gray.600", "var(--mon-color-gray-600)", ""],
  ["@color_primitives.Gray.700", "var(--mon-color-gray-700)", ""],
  ["@color_primitives.Gray.800", "var(--mon-color-gray-800)", ""],
  ["@color_primitives.Gray.900", "var(--mon-color-gray-900)", ""],
  ["@color_primitives.Green.100", "var(--mon-color-green-100)", ""],
  ["@color_primitives.Green.1000", "var(--mon-color-green-1000)", ""],
  ["@color_primitives.Green.200", "var(--mon-color-green-200)", ""],
  ["@color_primitives.Green.300", "var(--mon-color-green-300)", ""],
  ["@color_primitives.Green.400", "var(--mon-color-green-400)", ""],
  ["@color_primitives.Green.500", "var(--mon-color-green-500)", ""],
  ["@color_primitives.Green.600", "var(--mon-color-green-600)", ""],
  ["@color_primitives.Green.700", "var(--mon-color-green-700)", ""],
  ["@color_primitives.Green.800", "var(--mon-color-green-800)", ""],
  ["@color_primitives.Green.900", "var(--mon-color-green-900)", ""],
  ["@color_primitives.Pink.100", "var(--mon-color-pink-100)", ""],
  ["@color_primitives.Pink.1000", "var(--mon-color-pink-1000)", ""],
  ["@color_primitives.Pink.200", "var(--mon-color-pink-200)", ""],
  ["@color_primitives.Pink.300", "var(--mon-color-pink-300)", ""],
  ["@color_primitives.Pink.400", "var(--mon-color-pink-400)", ""],
  ["@color_primitives.Pink.500", "var(--mon-color-pink-500)", ""],
  ["@color_primitives.Pink.600", "var(--mon-color-pink-600)", ""],
  ["@color_primitives.Pink.700", "var(--mon-color-pink-700)", ""],
  ["@color_primitives.Pink.800", "var(--mon-color-pink-800)", ""],
  ["@color_primitives.Pink.900", "var(--mon-color-pink-900)", ""],
  ["@color_primitives.Red.100", "var(--mon-color-red-100)", ""],
  ["@color_primitives.Red.1000", "var(--mon-color-red-1000)", ""],
  ["@color_primitives.Red.200", "var(--mon-color-red-200)", ""],
  ["@color_primitives.Red.300", "var(--mon-color-red-300)", ""],
  ["@color_primitives.Red.400", "var(--mon-color-red-400)", ""],
  ["@color_primitives.Red.500", "var(--mon-color-red-500)", ""],
  ["@color_primitives.Red.600", "var(--mon-color-red-600)", ""],
  ["@color_primitives.Red.700", "var(--mon-color-red-700)", ""],
  ["@color_primitives.Red.800", "var(--mon-color-red-800)", ""],
  ["@color_primitives.Red.900", "var(--mon-color-red-900)", ""],
  ["@color_primitives.Slate.100", "var(--mon-color-slate-100)", ""],
  ["@color_primitives.Slate.1000", "var(--mon-color-slate-1000)", ""],
  ["@color_primitives.Slate.200", "var(--mon-color-slate-200)", ""],
  ["@color_primitives.Slate.300", "var(--mon-color-slate-300)", ""],
  ["@color_primitives.Slate.400", "var(--mon-color-slate-400)", ""],
  ["@color_primitives.Slate.500", "var(--mon-color-slate-500)", ""],
  ["@color_primitives.Slate.600", "var(--mon-color-slate-600)", ""],
  ["@color_primitives.Slate.700", "var(--mon-color-slate-700)", ""],
  ["@color_primitives.Slate.800", "var(--mon-color-slate-800)", ""],
  ["@color_primitives.Slate.900", "var(--mon-color-slate-900)", ""],
  ["@color_primitives.White.100", "var(--mon-color-white-100)", ""],
  ["@color_primitives.White.1000", "var(--mon-color-white-1000)", ""],
  ["@color_primitives.White.200", "var(--mon-color-white-200)", ""],
  ["@color_primitives.White.300", "var(--mon-color-white-300)", ""],
  ["@color_primitives.White.400", "var(--mon-color-white-400)", ""],
  ["@color_primitives.White.500", "var(--mon-color-white-500)", ""],
  ["@color_primitives.White.600", "var(--mon-color-white-600)", ""],
  ["@color_primitives.White.700", "var(--mon-color-white-700)", ""],
  ["@color_primitives.White.800", "var(--mon-color-white-800)", ""],
  ["@color_primitives.White.900", "var(--mon-color-white-900)", ""],
  ["@color_primitives.Yellow.100", "var(--mon-color-yellow-100)", ""],
  ["@color_primitives.Yellow.1000", "var(--mon-color-yellow-1000)", ""],
  ["@color_primitives.Yellow.200", "var(--mon-color-yellow-200)", ""],
  ["@color_primitives.Yellow.300", "var(--mon-color-yellow-300)", ""],
  ["@color_primitives.Yellow.400", "var(--mon-color-yellow-400)", ""],
  ["@color_primitives.Yellow.500", "var(--mon-color-yellow-500)", ""],
  ["@color_primitives.Yellow.600", "var(--mon-color-yellow-600)", ""],
  ["@color_primitives.Yellow.700", "var(--mon-color-yellow-700)", ""],
  ["@color_primitives.Yellow.800", "var(--mon-color-yellow-800)", ""],
  ["@color_primitives.Yellow.900", "var(--mon-color-yellow-900)", ""],
  ["@size.Blur.100", "var(--mon-size-blur-100)", ""],
  ["@size.Depth.0", "var(--mon-size-depth-0)", ""],
  ["@size.Depth.025", "var(--mon-size-depth-025)", ""],
  ["@size.Depth.100", "var(--mon-size-depth-100)", ""],
  ["@size.Depth.1200", "var(--mon-size-depth-1200)", ""],
  ["@size.Depth.200", "var(--mon-size-depth-200)", ""],
  ["@size.Depth.400", "var(--mon-size-depth-400)", ""],
  ["@size.Depth.800", "var(--mon-size-depth-800)", ""],
  ["@size.Depth.Negative 025", "var(--mon-size-depth-negative-025)", ""],
  ["@size.Depth.Negative 100", "var(--mon-size-depth-negative-100)", ""],
  ["@size.Depth.Negative 1200", "var(--mon-size-depth-negative-1200)", ""],
  ["@size.Depth.Negative 200", "var(--mon-size-depth-negative-200)", ""],
  ["@size.Depth.Negative 400", "var(--mon-size-depth-negative-400)", ""],
  ["@size.Depth.Negative 800", "var(--mon-size-depth-negative-800)", ""],
  ["@size.Icon.Large", "var(--mon-size-icon-large)", ""],
  ["@size.Icon.Medium", "var(--mon-size-icon-medium)", ""],
  ["@size.Icon.Small", "var(--mon-size-icon-small)", ""],
  ["@size.Radius.100", "var(--mon-size-radius-100)", ""],
  ["@size.Radius.200", "var(--mon-size-radius-200)", ""],
  ["@size.Radius.400", "var(--mon-size-radius-400)", ""],
  ["@size.Radius.Full", "var(--mon-size-radius-full)", ""],
  ["@size.Space.0", "var(--mon-size-space-0)", ""],
  ["@size.Space.050", "var(--mon-size-space-050)", ""],
  ["@size.Space.100", "var(--mon-size-space-100)", ""],
  ["@size.Space.1200", "var(--mon-size-space-1200)", ""],
  ["@size.Space.150", "var(--mon-size-space-150)", ""],
  ["@size.Space.1600", "var(--mon-size-space-1600)", ""],
  ["@size.Space.200", "var(--mon-size-space-200)", ""],
  ["@size.Space.2400", "var(--mon-size-space-2400)", ""],
  ["@size.Space.300", "var(--mon-size-space-300)", ""],
  ["@size.Space.400", "var(--mon-size-space-400)", ""],
  ["@size.Space.4000", "var(--mon-size-space-4000)", ""],
  ["@size.Space.600", "var(--mon-size-space-600)", ""],
  ["@size.Space.800", "var(--mon-size-space-800)", ""],
  ["@size.Space.Negative 100", "var(--mon-size-space-negative-100)", ""],
  ["@size.Space.Negative 200", "var(--mon-size-space-negative-200)", ""],
  ["@size.Space.Negative 300", "var(--mon-size-space-negative-300)", ""],
  ["@size.Space.Negative 400", "var(--mon-size-space-negative-400)", ""],
  ["@size.Space.Negative 600", "var(--mon-size-space-negative-600)", ""],
  ["@size.Stroke.Border", "var(--mon-size-stroke-border)", ""],
  ["@size.Stroke.Focus Ring", "var(--mon-size-stroke-focus-ring)", ""],
  ["@typography.Body.Font Family", "var(--mon-typography-body-font-family)", ""],
  ["@typography.Body.Font Style Italic", "var(--mon-typography-body-font-style-italic)", ""],
  ["@typography.Body.Font Weight Regular", "var(--mon-typography-body-font-weight-regular)", ""],
  ["@typography.Body.Font Weight Strong", "var(--mon-typography-body-font-weight-strong)", ""],
  ["@typography.Body.Size Large", "var(--mon-typography-body-size-large)", ""],
  ["@typography.Body.Size Medium", "var(--mon-typography-body-size-medium)", ""],
  ["@typography.Body.Size Small", "var(--mon-typography-body-size-small)", ""],
  ["@typography.Code.Font Family", "var(--mon-typography-code-font-family)", ""],
  ["@typography.Code.Font Weight", "var(--mon-typography-code-font-weight)", ""],
  ["@typography.Code.Size Base", "var(--mon-typography-code-size-base)", ""],
  ["@typography.Code.Size Large", "var(--mon-typography-code-size-large)", ""],
  ["@typography.Code.Size Small", "var(--mon-typography-code-size-small)", ""],
  ["@typography.Heading.Font Family", "var(--mon-typography-heading-font-family)", ""],
  ["@typography.Heading.Font Weight", "var(--mon-typography-heading-font-weight)", ""],
  ["@typography.Heading.Size Base", "var(--mon-typography-heading-size-base)", ""],
  ["@typography.Heading.Size Large", "var(--mon-typography-heading-size-large)", ""],
  ["@typography.Heading.Size Small", "var(--mon-typography-heading-size-small)", ""],
  ["@typography.Subheading.Font Family", "var(--mon-typography-subheading-font-family)", ""],
  ["@typography.Subheading.Font Weight", "var(--mon-typography-subheading-font-weight)", ""],
  ["@typography.Subheading.Size Large", "var(--mon-typography-subheading-size-large)", ""],
  ["@typography.Subheading.Size Medium", "var(--mon-typography-subheading-size-medium)", ""],
  ["@typography.Subheading.Size Small", "var(--mon-typography-subheading-size-small)", ""],
  ["@typography.Subtitle.Font Family", "var(--mon-typography-subtitle-font-family)", ""],
  ["@typography.Subtitle.Font Weight", "var(--mon-typography-subtitle-font-weight)", ""],
  ["@typography.Subtitle.Size Base", "var(--mon-typography-subtitle-size-base)", ""],
  ["@typography.Subtitle.Size Large", "var(--mon-typography-subtitle-size-large)", ""],
  ["@typography.Subtitle.Size Small", "var(--mon-typography-subtitle-size-small)", ""],
  ["@typography.Title Hero.Font Family", "var(--mon-typography-title-hero-font-family)", ""],
  ["@typography.Title Hero.Font Weight", "var(--mon-typography-title-hero-font-weight)", ""],
  ["@typography.Title Hero.Size", "var(--mon-typography-title-hero-size)", ""],
  ["@typography.Title Page.Font Family", "var(--mon-typography-title-page-font-family)", ""],
  ["@typography.Title Page.Font Weight", "var(--mon-typography-title-page-font-weight)", ""],
  ["@typography.Title Page.Size Base", "var(--mon-typography-title-page-size-base)", ""],
  ["@typography.Title Page.Size Large", "var(--mon-typography-title-page-size-large)", ""],
  ["@typography.Title Page.Size Small", "var(--mon-typography-title-page-size-small)", ""],
  ["@typography_primitives.Family Mono", "var(--mon-typography-family-mono)", ""],
  ["@typography_primitives.Family Sans", "var(--mon-typography-family-sans)", ""],
  ["@typography_primitives.Family Serif", "var(--mon-typography-family-serif)", ""],
  ["@typography_primitives.Scale 01", "var(--mon-typography-scale-01)", ""],
  ["@typography_primitives.Scale 02", "var(--mon-typography-scale-02)", ""],
  ["@typography_primitives.Scale 03", "var(--mon-typography-scale-03)", ""],
  ["@typography_primitives.Scale 04", "var(--mon-typography-scale-04)", ""],
  ["@typography_primitives.Scale 05", "var(--mon-typography-scale-05)", ""],
  ["@typography_primitives.Scale 06", "var(--mon-typography-scale-06)", ""],
  ["@typography_primitives.Scale 07", "var(--mon-typography-scale-07)", ""],
  ["@typography_primitives.Scale 08", "var(--mon-typography-scale-08)", ""],
  ["@typography_primitives.Scale 09", "var(--mon-typography-scale-09)", ""],
  ["@typography_primitives.Scale 10", "var(--mon-typography-scale-10)", ""],
  ["@typography_primitives.Weight Black Italic", "var(--mon-typography-weight-black-italic)", ""],
  ["@typography_primitives.Weight Black", "var(--mon-typography-weight-black)", ""],
  ["@typography_primitives.Weight Bold Italic", "var(--mon-typography-weight-bold-italic)", ""],
  ["@typography_primitives.Weight Bold", "var(--mon-typography-weight-bold)", ""],
  ["@typography_primitives.Weight Extra Bold Italic", "var(--mon-typography-weight-extra-bold-italic)", ""],
  ["@typography_primitives.Weight Extra Bold", "var(--mon-typography-weight-extra-bold)", ""],
  ["@typography_primitives.Weight Extra Light", "var(--mon-typography-weight-extra-light)", ""],
  ["@typography_primitives.Weight Extralight Italic", "var(--mon-typography-weight-extralight-italic)", ""],
  ["@typography_primitives.Weight Light Italic", "var(--mon-typography-weight-light-italic)", ""],
  ["@typography_primitives.Weight Light", "var(--mon-typography-weight-light)", ""],
  ["@typography_primitives.Weight Medium Italic", "var(--mon-typography-weight-medium-italic)", ""],
  ["@typography_primitives.Weight Medium", "var(--mon-typography-weight-medium)", ""],
  ["@typography_primitives.Weight Regular Italic", "var(--mon-typography-weight-regular-italic)", ""],
  ["@typography_primitives.Weight Regular", "var(--mon-typography-weight-regular)", ""],
  ["@typography_primitives.Weight Semibold Italic", "var(--mon-typography-weight-semibold-italic)", ""],
  ["@typography_primitives.Weight Semibold", "var(--mon-typography-weight-semibold)", ""],
  ["@typography_primitives.Weight Thin Italic", "var(--mon-typography-weight-thin-italic)", ""],
  ["@typography_primitives.Weight Thin", "var(--mon-typography-weight-thin)", ""],
].map(async ([variableId, webSyntax, description]) => {
  const variable = await figma.variables.getVariableByIdAsync(variableId);
  if (variable) {
    variable.setVariableCodeSyntax("WEB", webSyntax);
    variable.description = description;
  }
  return;
})).then(() => console.log("DONE!")).catch(console.error)